### ISSUE TITLE
installing requirements fails

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa-server#28]
The reason is a bogus line in requirements.txt:
`pkg-resources==0.0.0`

It seems that removing this line has no effect.

**Comment by BorderITS** [comment]
wow so let's try to fix it

**Comment by lcabrini** [comment]
Done. If some somebody can test this. If it works, I suggest approving.

**Comment by BorderITS** [comment]
yes it works well done Lorenzo!
